name: Main
on:
  push:
    branches:
      - main


jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Lint files
        run: yarn nx run-many --target lint --all

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn nx run-many --target test --all

  component-test:
    name: Component Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run component tests
        run: yarn nx run-many --target ct --all

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build apps
        run: yarn nx run-many --target build --all

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run E2E tests
        run: yarn nx run-many --target e2e --all
